### ISSUE TITLE
Problem for android 12

### ISSUE THREAD

**Issue by YourMomGay1104** [XayUp/MultiPad#1]
This pops up when I open the app on my android 12

nulljava.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1000, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.xayup.launchpadplus/com.xayup.launchpadplus.MainActivity}: java.lang.NullPointerException: Attempt to get length of null array

--------- Stack trace ---------

    android.app.ActivityThread.deliverResults(ActivityThread.java:5516)
    android.app.ActivityThread.handleSendResult(ActivityThread.java:5555)
    android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
    android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
    android.os.Handler.dispatchMessage(Handler.java:106)
    android.os.Looper.loopOnce(Looper.java:233)
    android.os.Looper.loop(Looper.java:344)
    android.app.ActivityThread.main(ActivityThread.java:8212)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
-------------------------------

--------- Cause ---------

java.lang.NullPointerException: Attempt to get length of null array

    com.xayup.launchpadplus.Readers.readInfo(Readers.java:58)
    com.xayup.launchpadplus.MainActivity.makeActivity(MainActivity.java:172)
    com.xayup.launchpadplus.MainActivity.onRequestPermissionsResult(MainActivity.java:217)
    android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8618)
    android.app.Activity.dispatchActivityResult(Activity.java:8475)
    android.app.ActivityThread.deliverResults(ActivityThread.java:5509)
    android.app.ActivityThread.handleSendResult(ActivityThread.java:5555)
    android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
    android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
    android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
    android.os.Handler.dispatchMessage(Handler.java:106)
    android.os.Looper.loopOnce(Looper.java:233)
    android.os.Looper.loop(Looper.java:344)
    android.app.ActivityThread.main(ActivityThread.java:8212)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
-------------------------------

**Comment by XayUp** [comment]
Set manually the permission of storage for "All media" in the permissions storage application

**Comment by YourMomGay1104** [comment]
Only just saw this comment just now
Thanks <3

**Comment by XayUp** [comment]
> Only just saw this comment just now
> Thanks <3

De nada <3. A próxima atualização corrige isso (e também funcionará no Android 13. Fiz os testes)
